Zorbus\ArticleBundle\Entity\Category:
    type: entity
    table: zorbus_article_category
    repositoryClass: Zorbus\ArticleBundle\Entity\CategoryRepository
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: false
        description:
            type: text
            nullable: true
        lang:
            type: string
            length: 5
            nullable: true
            default: en_US
        image:
            type: string
            length: 255
            nullable: true
        is_highlighted:
            type: boolean
            default: false
            nullable: true
        enabled:
            type: boolean
            default: true
            nullable: true
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel
        user_id:
            type: integer
            nullable: true
        slug:
            type: string
            length: 255
            nullable: true
            gedmo:
                slug:
                    separator: '-'
                    style: default
                    fields:
                        - name
        created_at:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks:
        prePersist: [preImageUpload]
        preUpdate: [preImageUpload]
        postPersist: [postImageUpload]
        postUpdate: [postImageUpload]
        postRemove: [postRemove]
    manyToOne:
        parent:
            targetEntity: Zorbus\ArticleBundle\Entity\Category
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: SET NULL
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: Zorbus\ArticleBundle\Entity\Category
            mappedBy: parent
            orderBy:
                lft: ASC
    manyToMany:
        articles:
            targetEntity: Article
            mappedBy: categories