Zorbus\ArticleBundle\Entity\Tag:
    type: entity
    table: zorbus_article_tag
    repositoryClass: Zorbus\ArticleBundle\Entity\TagRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        lang:
            type: string
            length: 5
            nullable: true
            default: en
        slug:
            type: string
            length: 255
            nullable: true
            gedmo:
                slug:
                    separator: '-'
                    style: default
                    fields:
                        - name
    manyToMany:
        articles:
            targetEntity: Article
            mappedBy: tags