parameters:
    zorbus_article.article.admin.class: Zorbus\ArticleBundle\Admin\ArticleAdmin
    zorbus_article.category.admin.class: Zorbus\ArticleBundle\Admin\CategoryAdmin
    zorbus_article.tag.admin.class: Zorbus\ArticleBundle\Admin\TagAdmin

    zorbus_article.article.entity.class: Zorbus\ArticleBundle\Entity\Article
    zorbus_article.category.entity.class: Zorbus\ArticleBundle\Entity\Category
    zorbus_article.tag.entity.class: Zorbus\ArticleBundle\Entity\Tag

    zorbus_article.article.controller.class: ZorbusArticleBundle:Admin
    zorbus_article.category.controller.class: SonataAdminBundle:CRUD
    zorbus_article.tag.controller.class: SonataAdminBundle:CRUD

    zorbus_block.service.article.class: Zorbus\ArticleBundle\Model\BlockArticleConfig
    zorbus_block.service.article.category.class: Zorbus\ArticleBundle\Model\BlockCategoryConfig

services:
    zorbus_article.article.admin:
        class: %zorbus_article.article.admin.class%
        arguments: [~, %zorbus_article.article.entity.class%, %zorbus_article.article.controller.class%]
        calls:
            - [setTranslationDomain, [ArticleBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Articles, label: Articles }
    zorbus_article.category.admin:
        class: %zorbus_article.category.admin.class%
        arguments: [~, %zorbus_article.category.entity.class%, %zorbus_article.category.controller.class%]
        calls:
            - [setTranslationDomain, [ArticleBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Articles, label: Categories }
    zorbus_article.tag.admin:
        class: %zorbus_article.tag.admin.class%
        arguments: [~, %zorbus_article.tag.entity.class%, %zorbus_article.tag.controller.class%]
        calls:
            - [setTranslationDomain, [ArticleBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Articles, label: Tags }
    zorbus_block.service.article:
        class: %zorbus_block.service.article.class%
        scope: prototype
        arguments: ['@zorbus_block.block.admin', '@form.factory', '@http_kernel']
        tags:
            - { name: zorbus_block.block, category: Articles }
    zorbus_block.service.article.category:
        class: %zorbus_block.service.article.category.class%
        scope: prototype
        arguments: ['@zorbus_block.block.admin', '@form.factory', '@http_kernel']
        tags:
            - { name: zorbus_block.block, category: Articles }
