<?php

namespace Zorbus\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function getArticles()
    {
        return $this->getEntityManager()->createQuery(
            'SELECT a, c, t FROM ZorbusArticleBundle:Article a LEFT JOIN a.categories c LEFT JOIN a.tags t WHERE a.is_enabled = :is_enabled AND a.status <> :draft ORDER BY a.date_published DESC'
        )
                ->setParameter('is_enabled', true)
                ->setParameter('draft', 'draft')
                ->getResult();
    }
    public function getArticlesWithTag($tag)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT a, c, t FROM ZorbusArticleBundle:Article a LEFT JOIN a.categories c JOIN a.tags t WITH t.slug = :tag WHERE a.is_enabled = :is_enabled AND a.status <> :draft ORDER BY a.date_published DESC'
        )
                ->setParameter('is_enabled', true)
                ->setParameter('draft', 'draft')
                ->setParameter('tag', $tag)
                ->getResult();
    }
    public function getArticlesWithCategory($category)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT a, c, t FROM ZorbusArticleBundle:Article a JOIN a.categories c WITH c.slug = :category LEFT JOIN a.tags t WHERE a.is_enabled = :is_enabled AND a.status <> :draft ORDER BY a.date_published DESC'
        )
                ->setParameter('is_enabled', true)
                ->setParameter('draft', 'draft')
                ->setParameter('category', $category)
                ->getResult();
    }
}
